### ISSUE TITLE
Find a better way to deallocate these pointers

### ISSUE THREAD

**Issue by natebird** [vapor-community/postgresql#11]
This isn't the best performant way to handle this but it works around the intermittent failures. We need a better way to do this.

https://github.com/vapor/postgresql/blob/master/Sources/PostgreSQL/Database.swift#L53-L61 and 
https://github.com/vapor/postgresql/blob/master/Sources/PostgreSQL/Database.swift#L91-L96.

**Comment by natebird** [comment]
It turns out that https://github.com/vapor/postgresql/blob/master/Sources/PostgreSQL/Database.swift#L53-L61 are not needed and everything works fine without those. However, we do need to look at L91-L96 to see if we can optimize that at all.

**Comment by natebird** [comment]
It may be a memory leak issue with L53-96 are needed to keep that under control. We need to test if we are leaking memory by removing those lines.

**Comment by natebird** [comment]
This issue will be fixed once #19 is approved.

**Comment by sroebert** [comment]
Fixed with #19
