### ISSUE TITLE
libpq-fe.h not found

### ISSUE THREAD

**Issue by TofPlay** [vapor-community/postgresql#24]
Hi
I have this error:
```
/Packages/CPostgreSQL-1.0.0/module.modulemap:8:12: error: header '/usr/include/postgresql/libpq-fe.h' not found
```

On ubuntu 16.04 I have installed:
```
apt-get install postgresql postgresql-client postgresql-contrib
```

What have I forgotten?

**Comment by TofPlay** [comment]
I fix it 😀

I changed:
```
apt-get install postgresql postgresql-client postgresql-contrib
```
by 
```
apt-get install postgresql postgresql-client postgresql-contrib libpq-dev
```

**Comment by natebird** [comment]
I updated the Readme in #25 to clarify this. Thanks @TofPlay for the update.

**Comment by gizmolab10** [comment]
after successfully running "apt-get install postgresql postgresql-client postgresql-contrib libpq-dev" which does install /usr/include/postgresql/libpq-fe.h, the following docker command fails (error follows)

docker build -t swift-on-ecs-prebuilt --build-arg SWIFT_VERSION=3.0-RELEASE .

/vapor/Packages/CPostgreSQL-1.0.0/module.modulemap:8:12: error: header '/usr/include/postgresql/libpq-fe.h' not found

apparently the above solution no longer works. anyone have anything that does?

**Comment by vzsg** [comment]
Wait a second. Running `apt-get install libpq-dev` on the _host_ system will not have any effect on the Docker build. You need to install the packages in the build containers with a RUN command.

**Comment by gizmolab10** [comment]
can you elaborate a bit for someone who is new to Vapor, Docker and SPM? i’ve been mostly doing client-side swift.
