### ISSUE TITLE
brew install postgresql

### ISSUE THREAD

**Issue by zhangzhaopds** [vapor-community/postgresql#26]
==> Downloading https://gist.githubusercontent.com/jacknagel/d886531fb6623b60b2a

curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "readline--patch"
Download failed: https://gist.githubusercontent.com/jacknagel/d886531fb6623b60b2af/raw/746fc543e56bc37a26ccf05d2946a45176b0894e/readline-6.3.8.diff

**Comment by natebird** [comment]
Did you get this resolved? You should be able to update homebrew with the `brew update` command. Then running `brew install postgresql` should work.

I'm going to close this since it seems to be a homebrew issue.
