### ISSUE TITLE
Incorrect result when parsing "NUMERIC" values

### ISSUE THREAD

**Issue by vzsg** [vapor-community/postgresql#47]
BinaryUtils.parseNumeric seems to return values with a completely off scale.
`600` for example becomes a String Node with `"0.0000000000000600"` inside.

I will upload a failing test case soon.

**Comment by t3ndai** [comment]
![screen shot 2017-06-12 at 14 30 48](https://user-images.githubusercontent.com/17970888/27048985-cf310ad2-4f7b-11e7-9bdc-c0c04dd6fe66.png)

Passing a Raw query like 
guard let collegeSet = try? Job.database?.raw("select college, avg(pay) as average from jobs group by college order by average desc").converted(to: JSON.self).makeResponse() else { throw SQL.serialization } 

produces off scale numbers.

**Comment by vzsg** [comment]
Fixed by #48, now available as 2.0.2.
