### ISSUE TITLE
PostgreSQL Vapor Packages won't compile after install

### ISSUE THREAD

**Issue by red3nzo** [vapor-community/postgresql#57]
I installed PostgreSQL on my Mac and installed the PostgreSQL provider to my project but after I run my project it says how `libpq-fe.h` isn't found and also I've noticed the whole `CPostgreSQL` folder is empty under `Dependencies`. It also says`Could not build Objective-C module CPostgreSQL` I'm guessing that's because the folder is empty. I have no clue how to fix this any any help would be greatly appreciated.

**Comment by vzsg** [comment]
The fact that CPostgreSQL is empty is normal, it's a system module so it has no visible sources in Xcode.

But how did you install Postgres? If you install it with Homebrew, and Homebrew is installed in the default location, things should just work. But only then.

**Comment by red3nzo** [comment]
@vzsg I used the PostgreSQL app from their website for MacOS. I'm guessing this has to do with the problem

**Comment by red3nzo** [comment]
Alright after an hour of looking I figured out the solution. Under `Dependencies` I installed the line `.Package(url: "https://github.com/vapor/postgresql.git", majorVersion: 2)` . 

*Full Code*

> dependencies: [
        .Package(url: "https://github.com/vapor/vapor.git", majorVersion: 2),
        .Package(url: "https://github.com/vapor/fluent-provider.git", majorVersion: 1),
        .Package(url: "https://github.com/vapor/postgresql.git", majorVersion: 2),
        .Package(url: "https://github.com/vapor-community/postgresql-provider.git", majorVersion: 2, minor: 0)
    ]
