### ISSUE TITLE
Examples don't show what to do with the result.

### ISSUE THREAD

**Issue by ADGrant** [vapor-community/postgresql#69]
E.g. call execute with a "select *" on a table to return a list of rows. How are the rows accessed.

**Comment by vzsg** [comment]
The execute method returns a Node (a very common type in Vapor 2), which contains an array or a null value.

For example:
```
let result = try conn.execute("SELECT * FROM foo f WHERE f.bar = $1", ["baz"]).array ?? []
// result is an [Node]
```

On how to extract values from the Nodes, you can check the [tests](https://github.com/vapor-community/postgresql/blob/master/Tests/PostgreSQLTests/PostgreSQLTests.swift).
