### ISSUE TITLE
Redirect old Repository to this one

### ISSUE THREAD

**Issue by strangfeld** [vapor-community/postgresql#71]
Hello Everyone,

could you please redirect https://github.com/vapor/postgresql.git to https://github.com/vapor-community/postgresql.git ?

Because the [postgresql-provider with version 1.1](https://github.com/vapor-community/postgresql-provider/tree/1.1.1) still depends on https://github.com/vapor/postgresql.git .. which is causing the Swift Package Manager to stall with no error for everyone using the postgresql-driver below version 2, since there is only an empty repository behind [](https://github.com/vapor/postgresql.git)

Greetings,
Robin

**Comment by Joannis** [comment]
@strangfeld that's not a temporary repository. We're writing a brand new PostgreSQL driver for Vapor 3 (written in Swift) [on the beta branch](https://github.com/vapor/postgresql/tree/beta)

**Comment by strangfeld** [comment]
@Joannis well i didnt realize that until now, then it should be safe to correct al the */vapor/* urls in the dependency chain to the */vapor-community/* ones ....

**Comment by vzsg** [comment]
Yes. That's exactly what's happening right now, stay tuned.
